---
title: "ASER variance - create combined graphs"
output: html_notebook
---

This notebook uses data outputs from the "ASER variance over time" notebook to create combined graphs showing both math and reading

```{r setup}
library(tidyverse)
path <- "C:/Users/dougj/Dropbox/Education in India/Original research/Learning outcomes data/figures"
math_bar_data <- read_csv(file.path(path, "math - bar data.csv"))
math_bar_data$subject <- "Math"

reading_bar_data <- read_csv(file.path(path, "reading - bar data.csv"))
reading_bar_data$subject <- "Reading"
bar_data <- rbind(math_bar_data, reading_bar_data) 


math_var_deco <- read_csv(file.path(path, "math - var deco.csv"))
math_var_deco$subject <- "Math"


reading_var_deco <- read_csv(file.path(path, "reading - var deco.csv"))
reading_var_deco$subject <- "Reading"

var_deco <- rbind(math_var_deco, reading_var_deco)
```

Create bar graph
```{r}
# Change the bar_part variable to an ordered factor
bar_data <- bar_data %>%
  mutate(bar_part_ordered = factor(bar_part, ordered = TRUE, levels = c("Transitory other","Transitory sampling", "Persistent")))


ggplot(bar_data, aes(fill = bar_part_ordered, y=value, x= changes_or_levels)) +
  geom_bar(position="stack", stat ="identity") +
  facet_grid( subject ~ state_or_dist) + 
  scale_fill_manual(values = c("red", "orange", "blue"))+
  labs(fill = "Variance component", x = "", y = "Variance") 

ggsave("Combined bar chart.png", width = 7, height = 6 , path = path)
```

Output table with combined results for var deco.  
```{r}
df <- var_deco %>% select(state_or_dist, changes_or_levels, subject, starts_with("share"))
write_csv(df, file.path(path, "combined var deco.csv"))
```

