---
title: "Simulate effect of variance on state rankings"
output: html_notebook
---

Using the estimates from the variance decomposition, use simulation to estimate the effect this would have on the accuracy of splitting up states into bottom quartile, middle 50%, and top quartile


### Import data on variance and set parameters

```{r setup, results='hide'}
library(tidyverse)
library(rlang)
path <- "C:/Users/dougj/Dropbox/Education in India/Original research/Learning outcomes data/figures"

# Inputs
n <- 100000
centile <- .25
subject <- "math"
levels_changes <- "Changes"
state_dist <- "District"
dist_type <- "normal"


# Read in and grab the appropriate variance figures
df <- read_csv(file.path(path, paste(subject, " - var deco.csv", sep = ""))) %>% 
  filter((state_or_dist == state_dist) & (changes_or_levels == levels_changes))

var_pers <- df$Persistent[1]
var_trans <- df$`Transitory sampling`[1] + df_row$`Transitory other`[1]

print(var_pers/var_trans)
```


```{r}

# Create a dataframe of draws using the estimates of variance and the appropriate distribution type

if (dist_type == "normal"){
  draws <- data.frame(pers = rnorm(n, mean = 0, sd = var_pers^.5),
             trans = rnorm(n, mean = 0, sd = var_trans^.5))
  
} else if (dist_type == "beta") {
  # with the beta, var = shape1*shape2 / [(shape1+shape2)^2*(shape1 + shape2 + 1)]
  # note that if mean = .5 then shape1 =  shape2 with the beta.  
  # Thus, to simplify things, I assume that the mean is .5.
  # With this simplification, var = shape^2/[4shape^2*(2*shape+1)]=1/[8*shape+4]
  # and shape = (1/8*var)-.5
    
  shape_pers <- (1/(8*var_pers))-.5
  shape_trans <- (1/(8*var_trans))-.5
  draws <- data.frame(pers = rbeta(n, shape_pers, shape_pers),
               trans = rbeta(n, shape_trans, shape_trans))
} else {
  print("Couldn't match dist type")
}

# Create y, which is the measured score
draws <- draws %>% mutate(y = pers +trans)
# Create rank of measured score
draws$y_rank[order(draws$y)] <- 1:nrow(draws)
# Create rank of "true" score
draws$pers_rank[order(draws$pers)] <- 1:nrow(draws)
# Create binaries for whether true and measured scores are in the top centile
draws <- draws %>%
  mutate(top_cent_pers = (pers_rank > (1-centile)*n), top_cent_y = (y_rank > (1-centile)*n))

# Calculate accuracy as the percentage of actual 
accuracy <- mean(draws$top_cent_pers[draws$top_cent_y])
cat("Reporting accuracy as the proportion of those actually in the top centile which would be ranked as being in the top centile.\n\n")
cat("Inputs:::: \n")
cat("centile: ", centile, "\n")
cat("Distribution: ", dist_type, "\n")
cat("States or districts: ", state_dist, "\n")
cat("Subject: ", subject, "\n")
cat("Deltas or levels:", levels_changes, "\n\n")

cat("accuracy is", accuracy)

```

