---
title: "State level regressions"
output: html_notebook
---

Initial state-level regressions

```{r setup}
library(tidyverse)
library(plm)
library(broom)
data_path <- "C:/Users/dougj/Documents/Data/Education"
states <- read_csv(file.path(data_path, "ASER trends over time", "aser_trends.csv"))
```


Loop over all of the outcomes. Use both within and first differencing. Run with and without MP.


```{r}

outcomes <- str_subset(names(states), "^std.*all$")
states <- states %>%
  mutate(state_factor = as.factor(State), year_factor = as.factor(year)) 

# remove MP since it is a big outlier
states <- states %>% filter

for (y in outcomes) {
  print(y)
  # create string of formula. 
  rx <- paste(y, "~ state_factor + pvt")
  
  print("Without MP")
  fit_no_mp <- plm(rx, data = states, subset = (State != "madhyapradesh"), index = "state_factor")
  fit_no_mp_tidy <- tidy(fit_no_mp)
  print(fit_no_mp_tidy[fit_no_mp_tidy$term == "pvt",])

  
  print("With MP")
  fit_with_mp <- plm(rx, data = states, index = "state_factor")
  fit_tidy <- tidy(fit_no_mp)
  print(fit_no_mp_tidy[fit_no_mp_tidy$term == "pvt",])
  
  
}


```